gitops-demo:
  image:
    repository: registry.baloise.dev/example/gitops-nginx-demo
    tag: 16d4657ebb76151587a3483e035e1e1bd737dca2
  replicaCount: 1
  network:
    http:
      servicePort: 8080
      ingress:
        host: gitops-nginx-demo-bb56843c.apps.okd.baloise.dev
