gitops-demo:
  image:
    repository: registry.baloise.dev/example/gitops-nginx-demo
    tag: 50a2697f6497b3bd3a94e982eee88a32dea5a381
  replicaCount: 1
  network:
    https:
      servicePort: 8443
      ingress:
        host: demo-test.apps.baloise.dev
  tlsSidecar:
    enabled: true
