gitops-demo:
  image:
    repository: registry.baloise.dev/example/gitops-nginx-demo
    tag: 01
  replicaCount: 0
  network:
    https:
      servicePort: 8443
      ingress:
        host: demo-test.apps.baloise.dev
  tlsSidecar:
    enabled: true
