gitops-demo:
  image:
    repository: registry.baloise.dev/example/gitops-nginx-demo
    tag: latest
  replicaCount: 5
  ingress:
    enabled: true
    host: gitops-nginx-demo-test.apps.okd.baloise.dev
