gitops-demo:
  image:
    repository: registry.baloise.dev/example/gitops-nginx-demo
    tag: 4cd4a8c7aaf118fe29e56d97001ffd88e65c410b
  replicaCount: 1
  network:
    http:
      servicePort: 8080
      ingress:
        host: demo-test.apps.baloise.dev
