gitops-demo:
  image:
    repository: registry.baloise.dev/example/gitops-nginx-demo
    tag: a9f53097d5c247558818e21631bb1ebe641a3c9d
  replicaCount: 1
  network:
    http:
      servicePort: 8080
      ingress:
        host: demo-test.apps.baloise.dev
