devops-octopus:
  image:
    repository: baloiseincubator/devops-octopus
    tag: fbf2213303d3fd70fde3c7e6153d918380d54316
  ingress:
    enabled: true
    host: octopus-30980c70.apps.okd.baloise.dev
    path: /api
devops-butterfly:
  image:
    repository: baloiseincubator/devops-butterfly
    tag: latest
  ingress:
    enabled: true
    host: octopus-30980c70.apps.okd.baloise.dev
