gitops-demo:
  image:
    repository: registry.baloise.dev/example/gitops-nginx-demo
    tag: 309bad1d427afd2fa0071cd179a5c4bffa8260d8
  replicaCount: 1
  network:
    http:
      servicePort: 8080
      ingress:
        host: gitops-nginx-demo-cd168e77.apps.okd.baloise.dev
