devops-octopus:
  image:
    repository: baloiseincubator/devops-octopus
    tag: latest
  ingress:
    enabled: true
    host: octopus-47c43cc1.apps.okd.baloise.dev
    path: /api
devops-butterfly:
  image:
    repository: baloiseincubator/devops-butterfly
    tag: ec2bd514e367c834c8edcdfbc7ac5a4e687f2fc6
  ingress:
    enabled: true
    host: octopus-47c43cc1.apps.okd.baloise.dev
