devops-octopus:
  image:
    repository: baloiseincubator/devops-octopus
    tag: latest
  ingress:
    enabled: true
    host: octopus-b252f270.baloise.dev
    path: /api
devops-butterfly:
  image:
    repository: baloiseincubator/devops-butterfly
    tag: f4c21f350cdaf8227cadefd64884aafa99c0f4c9
  ingress:
    enabled: true
    host: octopus-b252f270.baloise.dev
