gitops-demo:
  image:
    repository: registry.baloise.dev/example/gitops-nginx-demo
    tag: d631a185928ba5a228d2d8245f1a59225de3df04
  replicaCount: 1
  network:
    http:
      servicePort: 8080
      ingress:
        host: gitops-nginx-demo-c7003101.apps.okd.baloise.dev
