devops-octopus:
  image:
    repository: baloiseincubator/devops-octopus
    tag: fac61242f2029736a9fda37c3d7ca99b7dfe5582
  ingress:
    enabled: true
    host: octopus-9f86d081.apps.okd.baloise.dev
    path: /api
devops-butterfly:
  image:
    repository: baloiseincubator/devops-butterfly
    tag: latest
  ingress:
    enabled: true
    host: octopus-9f86d081.apps.okd.baloise.dev
