apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: hardwired-artifact-
spec:
  entrypoint: hardwired-artifact
  templates:
    - name: hardwired-artifact
      inputs:
        artifacts:
          - name: example-apps
            path: /example-apps
            git:
              repo: https://github.com/baloise-incubator/okd4-example-apps.git
              revision: "master"
      container:
        image: debian
        command: [sh, -c]
        args: ["ls -l /piza-orders/"]