devops-octopus:
  image:
    repository: baloiseincubator/devops-octopus
    tag: latest
  ingress:
    enabled: true
    host: octopus-83103e1d.apps.okd.baloise.dev
    path: /api
devops-butterfly:
  image:
    repository: baloiseincubator/devops-butterfly
    tag: 20dce00ff3b3aa1a57b33ec2a596bc24d25e5a8e
  ingress:
    enabled: true
    host: octopus-83103e1d.apps.okd.baloise.dev
