devops-octopus:
  image:
    repository: baloiseincubator/devops-octopus
    tag: latest
  ingress:
    enabled: true
    host: octopus-83103e1d.apps.okd.baloise.dev
    path: /api
devops-butterfly:
  image:
    repository: baloiseincubator/devops-butterfly
    tag: 54c9407f3c2c63639705458cbe48e923e046eaf6
  ingress:
    enabled: true
    host: octopus-83103e1d.apps.okd.baloise.dev
