devops-octopus:
  image:
    repository: baloiseincubator/devops-octopus
    tag: 009a07244f691e4b38fea3bef8e91bd46ecdaf96
  ingress:
    enabled: true
    host: octopus-b1c3392d.apps.okd.baloise.dev
    path: /api
devops-butterfly:
  image:
    repository: baloiseincubator/devops-butterfly
    tag: 25f1d0b7668ce8883ce93d26debb0bf3f84f4e3a
  ingress:
    enabled: true
    host: octopus-b1c3392d.apps.okd.baloise.dev
