gitops-demo:
  image:
    repository: registry.baloise.dev/example/gitops-nginx-demo
    tag: 6c237d161cc99938b85f41f4192ebdf0f5e3ddc3
  replicaCount: 1
  network:
    http:
      servicePort: 8080
      ingress:
        host: gitops-nginx-demo-d0c62789.apps.okd.baloise.dev
