gitops-demo:
  image:
    repository: registry.baloise.dev/example/gitops-nginx-demo
    tag: 89abecf8e1f1bf900653d2e91d3db29d5c9e62df
  replicaCount: 1
  network:
    http:
      servicePort: 8080
      ingress:
        host: gitops-nginx-demo-a6239b0a.apps.okd.baloise.dev
