gitops-demo:
  image:
    repository: registry.baloise.dev/example/gitops-nginx-demo
    tag: thisispreviewspecific
  replicaCount: 1
  network:
    http:
      servicePort: 8080
      ingress:
        host: thisispreviewspecific
