devops-octopus:
  image:
    repository: baloiseincubator/devops-octopus
    tag: latest
  ingress:
    enabled: true
    host: octopus-previewplaceholder.apps.okd.baloise.dev
    path: /api
devops-butterfly:
  image:
    repository: baloiseincubator/devops-butterfly
    tag: latest
  ingress:
    enabled: true
    host: octopus-previewplaceholder.apps.okd.baloise.dev