devops-octopus:
  image:
    repository: baloiseincubator/devops-octopus
    tag: latest
  network:
    http:
      servicePort: 8080
      ingress:
        host: octopus-preview.apps.baloise.dev
        path: /api
devops-butterfly:
  image:
    repository: baloiseincubator/devops-butterfly
    tag: latest
  network:
    http:
      servicePort: 8080
      ingress:
        host: octopus-preview.apps.baloise.dev
        path: /